//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarbucksScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegularHour
    {
        public int Id { get; set; }
        public int StoreID { get; set; }
        public string Day { get; set; }
        public bool Open { get; set; }
        public bool Open24Hours { get; set; }
        public string OpenTime { get; set; }
        public string CloseTime { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
